apiVersion: v1
kind: Pod
metadata:
  name: nnappone
  labels:
   app: nnappone
spec:
  containers:
    - name: gstraning-app
      image: ghanshyamit100/customwebserver:v1
      resources:
        limits:
          cpu: "10"
        requests:
          cpu: "10"
          
#pod must be in running state
