apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: ghanshyamit100/customwebserver:v1
      volumeMounts:
      - mountPath: "/var/www/html"
        name: webroot
  volumes:
    - name: webroot
      persistentVolumeClaim:
        claimName: myclaim
